config/routes.rb
Houston::SupportForm::Engine.routes.draw do

  scope "support_form" do
    get "" => "requests#index"
    get "/:project" => "requests#new", as: :project_support

    post "/itsm" => "itsms#create"
  end

end

app/controllers/houston/support_form/application_controller.rb
module Houston::SupportForm
  class ApplicationController < ::ApplicationController
    layout "houston/support_form/application"
  end
end

app/controllers/houston/support_form/itsms_controller.rb
module Houston
  module SupportForm
    class ItsmsController < Houston::SupportForm::ApplicationController

      def create
        issue_url = ITSM::Issue.create(
          username: current_user.username,
          summary: params[:summary],
          notes: params[:text])
        render json: {url: issue_url}
      end

    end
  end
end

app/controllers/houston/support_form/requests_controller.rb
module Houston
  module SupportForm
    class RequestsController < Houston::SupportForm::ApplicationController
      attr_reader :project
      before_action :authenticate_user!

      def index
        @projects = followed_projects
      end

      def new
        @project = Project.find_by_slug params[:project]
        return render file: "public/404.html" unless @project

        # BEGIN COPIED FROM project_tickets_controller#new
        unless @project.has_ticket_tracker?
          render template: "houston/tickets/project_tickets/no_ticket_tracker"
          return
        end

        Houston.benchmark "Load tickets" do
          @tickets = @project.tickets
            .where(type: "Bug")
            .pluck(:id, :summary, :number, :closed_at)
            .map do |id, summary, number, closed_at|
            { id: id,
              summary: summary,
              closed: closed_at.present?,
              ticketUrl: @project.ticket_tracker_ticket_url(number),
              number: number }
          end
        end
        # END COPIED FROM project_tickets_controller#new

        # BEGIN COPIED FROM project_feedback_controller#index
        @tags = Houston::Feedback::Conversation.for_project(project).tags
        # END COPIED FROM project_feedback_controller#index
      end

    end
  end
end

app/helpers/houston/support_form/application_helper.rb
module Houston::SupportForm
  module ApplicationHelper
  end
end

app/views/houston/support_form/requests/index.html.erb
<% content_for :title do %>
<h1 class="project-banner space-below">
  <small>New Ticket</small>
  
  <%= render partial: "projects/keyboard_shortcuts" %>
</h1>
<% end %>

<div class="project-tiles">
  <% @projects.each do |project| %>
    <%= link_to project.name, project_support_path(project), :class => "project-tile #{project.color}" %>
  <% end %>
</div>

<div class="tip">
  <h6>Don't see the project you want to create a ticket for?</h6>
  You might need to <%= link_to "follow it", main_app.projects_path %>.
</div>

app/views/houston/support_form/requests/new.html.erb
<%= render partial: "projects/header", locals: {project: @project, subtitle: "New Ticket for", without: %w{new_ticket keyboard_shortcuts}} %>

<div id="support_form">
  <ul class="nav nav-pills">
    <li class="active">
      <a href="#feedback" data-toggle="tab">
        <i class="fa fa-comment"></i>
        <h4>Feedback</h4>
        <p>for most things</p>
      </a>
    </li>
    <li>
      <a href="#itsm" data-toggle="tab">
        <i class="fa fa-fire-extinguisher"></i>
        <h4>ITSM</h4>
        <p>for <u data-toggle="tooltip" data-placement="bottom" data-original-title="A recent release broke existing functionality">Regressions</u>, <u data-toggle="tooltip" data-placement="bottom" data-original-title="The customer is seeing an error message">Errors</u>, or Tier 2 support</p>
      </a>
    </li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="feedback">
      <form id="new_feedback_form" class="container-fluid">
        <div class="row-fluid">
          <label class="control-label span2" for="new_feedback_customer">Customer</label>
          <div class="span6 controls">
            <input type="text" id="new_feedback_customer" name="attributedTo" placeholder="GM 00349061 "/>
          </div>
          <div class="span4 help overlap-below">
            If the feedback is from <em>you</em>, leave this field blank. Otherwise, enter something that <u>uniquely</u> identifies a person like an <b>email address</b> or <b>Goldmine case</b>.
          </div>
        </div>

        <div class="row-fluid">
          <label class="control-label span2" for="new_feedback_text">Text</label>
          <div class="span6 controls">
            <div class="uploader">
              <textarea id="new_feedback_text" name="text"></textarea>
            </div>
          </div>
        </div>

        <div class="row-fluid">
          <label class="control-label optional span2" for="new_feedback_tags">Tags</label>
          <div class="span6 controls">
            <input type="text" id="new_feedback_tags" class="feedback-new-tag" />
          </div>
          <div class="span4 help">
            You can enter multiple tags by separating them with commas.
          </div>
        </div>
      </form>

      <div class="buttons">
        <button type="button" id="clear_feedback" class="btn btn-default" data-dismiss="modal">Clear</button>
        <button type="button" id="create_feedback" class="btn btn-primary">Submit</button>
      </div>
    </div>



    <div class="tab-pane" id="itsm">
      <form id="new_itsm_form" class="container-fluid">
        <div class="row-fluid">
          <label class="control-label span2" for="new_itsm_summary">Summary</label>
          <div class="span10 controls">
            <input type="text" id="new_itsm_summary" name="summary" />
          </div>
        </div>

        <div class="row-fluid">
          <label class="control-label span2" for="new_itsm_text">Text</label>
          <div class="span10 controls">
            <div class="uploader">
              <textarea id="new_itsm_text" name="text"></textarea>
            </div>
          </div>
        </div>
      </form>

      <div class="buttons">
        <button type="button" id="clear_itsm" class="btn btn-default" data-dismiss="modal">Clear</button>
        <button type="button" id="create_itsm" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>


<% content_for :javascripts do %>
<script type="text/javascript">
  $(function() {
    var project = {
      slug: <%= raw @project.slug.to_json %>,
      ticketTrackerName: <%= raw @project.ticket_tracker_name.to_json %><%# so that we can log in %>
    };
    new Houston.SupportForm.View({
      tags: <%=raw @tags.to_json %>,
      project: project
    }).render();
  });
</script>
<% end %>

app/views/layouts/houston/support_form/application.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag    "houston/support_form/application", :media => "all" %>
  <%= stylesheet_link_tag    "houston/feedback/application", :media => "all" %>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag "houston/support_form/application" %>
  <%= javascript_include_tag "houston/feedback/application" %>
<% end %>

<%# Houston's default layout %>
<%= render template: "layouts/application" %>